### ISSUE TITLE
Benchmarking the AES module

### ISSUE THREAD

**Issue by Schmid7k** [RustCrypto/block-ciphers#309] opened 2022-02-25 17:19 UTC
Hello everyone, I am currently trying to benchmark RustCrypt's AES module (atm ECB mode only) for some research I am conducting on Rust's crypto ecosystem. For this purpose I wrote a program that was supposed to behave similar to `openssl speed` in terms of output. However, it seems that I reached a performance dead-end and/or some weird behaviour I can't really explain.

Let me begin with the output of `openssl speed -evp aes-128-ecb`:

- Doing aes-128-ecb for 3s on 16 size blocks: 189_494_781 aes-128-ecb's in 2.99s

Now, the following is one version of my code:

```rust
    let mut block = GenericArray::from([
        0x52, 0x62, 0x12, 0x65, 0x12, 0x23, 0x65, 0x62, 0x12, 0x75, 0x75, 0x87, 0x11, 0x01, 0x12,
        0x34,
    ]);
    let key = GenericArray::from([
        0x12, 0x63, 0x12, 0x65, 0x19, 0x23, 0x55, 0x62, 0x12, 0x75, 0x79, 0x97, 0x11, 0x41, 0x17,
        0x34,
    ]);
    let cipher = Aes128::new(&key);

    let mut counter: u128 = 0;
    let end = Duration::from_secs(3);
    let now = Instant::now();

    while now.elapsed() < end {
        cipher.encrypt_block(&mut block);
        counter += 1;
    }

    let time = now.elapsed();
    println!(
        "Doing aes-128-ecb for 3s on {} size blocks: {} aes-128-ecb's in {:.2?}",
        block.len(),
        counter,
        time
    );
```
This would give me the following output:

- Doing aes-128-ecb for 3s on 16 size blocks: 144_595_681 aes-128-ecb's in 3.00s

As you can see, there's a difference of 45 million blocks between my benchmark and openssl speed.

However, I thought that the calls to `now.elapsed()` may impose quite the overhead overtime, therefore I created another benchmark in which I just encrypted a large amount of blocks and measured how long it took.

```rust
    let mut block = GenericArray::from([
        0x52, 0x62, 0x12, 0x65, 0x12, 0x23, 0x65, 0x62, 0x12, 0x75, 0x75, 0x87, 0x11, 0x01, 0x12,
        0x34,
    ]);
    let mut blocks = vec![block; 1_200_000_000];
    let key = GenericArray::from([
        0x12, 0x63, 0x12, 0x65, 0x19, 0x23, 0x55, 0x62, 0x12, 0x75, 0x79, 0x97, 0x11, 0x41, 0x17,
        0x34,
    ]);
    let cipher = Aes128::new(&key);

    let mut counter: u128 = 0;
    let now = Instant::now();
    
    for block in blocks.iter_mut() {
        cipher.encrypt_block(block);
        counter += 1;
    }

    let time = now.elapsed();
    println!(
        "Doing aes-128-ecb for 3s on {} size blocks: {} aes-128-ecb's in {:.2?}",
        block.len(),
        counter,
        time
    );
``` 
Now this would give the following output:

- Doing aes-128-ecb for 3s on 16 size blocks: 1_200_000_000 aes-128-ecb's in 3.20s

!!! 1_200_000_000 !!! blocks in 3.2 seconds. Now I am pretty sure that something's not right here, however I am not able to pinpoint it down correctly and I already asked on some other forums but noone was really able to help so I was wondering if someone from the team could take a look at it and maybe help me out.

I also executed the benchmarks provided by the crate with `cargo bench` and got the following output:

```bash
test aes128_decrypt_block  ... bench:       2,291 ns/iter (+/- 3) = 7151 MB/s
test aes128_decrypt_blocks ... bench:       2,183 ns/iter (+/- 0) = 7505 MB/s
test aes128_encrypt_block  ... bench:       2,305 ns/iter (+/- 6) = 7108 MB/s
test aes128_encrypt_blocks ... bench:       2,183 ns/iter (+/- 0) = 7505 MB/s
test aes128_new            ... bench:          47 ns/iter (+/- 0)

```

**Comment by tarcieri** [comment] 2022-02-25 19:22
For competitive benchmarking, I'd recommend using [`criterion`](https://github.com/bheisler/criterion.rs) with the [`criterion-cycles-per-byte`](https://gitlab.com/sio4/code/criterion-cycles-per-byte) plugin. See here for an example:

https://github.com/RustCrypto/AEADs/tree/master/benches

Generally CPU cycles/byte are the standard way of measuring cipher performance.

**Comment by newpavlov** [comment] 2022-02-25 21:59
Try to use the `encrypt_blocks` method, not to iterate over blocks with `encrypt_block`. It should be a bit more efficient.

As for your last result, try to use `test::black_box` on the resulting blocks. Rust compiler probably can see that the encryption is a pure function and that its result are not used in any way, so it eliminates the loop completely.

**Comment by Schmid7k** [comment] 2022-02-26 11:27
@tarcieri The cycles per byte part would have been the next step on my research journey, this is currently just a bit of playing around, getting familiar with the structs and how to use the different libraries etc.

I was actually already trying out some things with `criterion` though I did not know that there was a plugin for CPB. This is definitely going to be helpful and I since I am trying to bench it anyways might as well contribute the aftermath to this repo if it turns out ok!

**Comment by newpavlov** [comment] 2022-02-26 14:35
>I am just looking for serial encryption speed

Are you sure that OpenSSL does not use parallel processing of blocks as well? Note that "parallel" here is done using one core using [ILP](https://en.wikipedia.org/wiki/Instruction-level_parallelism) and SIMD. Getting true "serial" encryption speed for ECB mode will be difficult since modern CPUs use [out-of-order execution](https://en.wikipedia.org/wiki/Out-of-order_execution). I would suggest measuring performance of the CBC mode of operation which contains data dependencies between processed blocks.

**Comment by Schmid7k** [comment] 2022-02-27 16:04
But how do you explain `openssl speed` "only" being able to encrypt around ~190 mill of blocks in 3 seconds, while I am able to encrypt 1_200_000_000 blocks of the same size in Rust in roughly the same time? This seems kinda fishy to me, almost as if something is not behaving the way it should but I can't pinpoint what exactly it is.

**Comment by tarcieri** [comment] 2022-02-27 16:07
That's why it would be nice to have competitive benchmarks checked in for comparison, so it's possible to reproduce them and investigate them

**Comment by newpavlov** [comment] 2022-02-27 16:21
On my CPU `openssl speed -evp aes-128-ecb` produces the following result:
```
Doing aes-128-ecb for 3s on 16 size blocks: 185448853 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 64 size blocks: 189152563 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 256 size blocks: 118446706 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 1024 size blocks: 32228411 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 8192 size blocks: 4475402 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 16384 size blocks: 2212301 aes-128-ecb's in 3.00s
```
Computing `2212301 * 16384 / 3 / 10^9` gives us ~12 GB/s. It's faster than results of `cargo bench` (~10 GB/s), so I am not 100% sure if it's an apples-to-apples comparison, but numbers look comparable.

For 16 byte blocks we get 0.92 GB/s, but such slowdown is expected, especially if OpenSSL executes syscall after encrypting 16 bytes (one block).

**Comment by Schmid7k** [comment] 2022-02-27 16:48
Ok so I tried to recreate the benchmarks from here https://github.com/RustCrypto/AEADs/tree/master/benches for `aes-ecb` with a starting block size of 16 byte. Now I get some promising results and this already looks a lot better in terms of reproduction.

This is the benchmark code I produced (of course the for loop is unnecessary atm but I will extend it later anyways): 

```rust
const KB: usize = 16;

fn bench(c: &mut Criterion<CyclesPerByte>) {
    let mut group = c.benchmark_group("aes-ecb");

    for size in &[KB] {
        let vec = vec![0u8; *size];
        let mut buf = *GenericArray::from_slice(&vec[..vec.len()]);

        group.throughput(Throughput::Bytes(*size as u64));

        group.bench_function(BenchmarkId::new("encrypt-128", size), |b| {
            let cipher = Aes128::new(&Default::default());
            b.iter(|| cipher.encrypt_block_b2b(&Default::default(), &mut buf))
        });
    }
}
```

And here are the results:

```bash
aes-ecb/encrypt-128/16  time:   [8.8800 cycles 8.8823 cycles 8.8856 cycles]                        
                        thrpt:  [0.5553 cpb 0.5551 cpb 0.5550 cpb]
```

**Comment by newpavlov** [comment] 2022-02-27 17:17
You are doing it wrong...

Do not encrypt one block, you get a big overhead, which is not relevant to real world usage. Allocate a bigger buffer of blocks and work over it. Also do not use buffer-to-buffer mode of operation if you want apples-to-apples comparison with OpenSSL. Do not work on a `Default::default()` block, compiler could perform optimizations which will distort the measurement results.

Here how benchmark could look like:
```rust
fn bench(c: &mut Criterion<CyclesPerByte>) {
    let mut group = c.benchmark_group("aes128-ecb-encrypt");

    let cipher = Aes128Enc::new(&Default::default());
    for &size in &[KB, 2 * KB, 4 * KB, 8 * KB, 16 * KB] {
        let mut buf = vec![Default::default(); size / 16];
        group.throughput(Throughput::Bytes(size as u64));
        group.bench_function(BenchmarkId::new("encrypt_blocks", size), |b| {
            b.iter(|| cipher.encrypt_blocks(&mut buf));
        });
    }
    group.finish();
}
```

Also for good benchmarking it's important to disable hyperthreading and adaptive CPU frequency.

I think we can close this issue. I suggest asking further questions on [URLO](https://users.rust-lang.org).

**Closed** 2022-02-27 17:19 UTC
